---
- name: Run command and print to terminal window
  hosts: routers
  gather_facts: false
  vars:
    data: "{{ lookup('file', 'json/data.json') }}"
    ospf_network: "{{ data.ospf_network }}"

  tasks:
    - name: configure interface settings
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ospf_network[inventory_hostname] }}"