---
- name: send config command
  hosts: routers
  gather_facts: false

  tasks:
    # - name: configure interface settings
    #   ios_config:
    #     lines:
    #       - description test config loopback
    #       - ip address 172.31.1.1 255.255.255.0
    #     parents: interface Loopback1
    
    - name: config routing protocol OSPF
      ios_config:
        lines:
          - network 10.0.15.0 0.0.0.255 area 0
          - network 192.168.99.0 0.0.0.255 area 0
        parents: router ospf 1
            