---
- name: Run command and print to terminal window
  hosts: routers
  gather_facts: false

  tasks:
    - name: show multiple command
      ios_command:
        commands:
          - sh ip int br
          - sh run | sect ospf
          - sh run | sect dhcp

      register: results
    
    - name: display
      debug:
        var: results.stdout_lines
