---
- name: send config command
  hosts: routers
  gather_facts: false
  vars:
    data: "{{ lookup('file', 'json/data.json') }}"
    ospf_network: "{{ data.ospf_network }}"
    ip_int_g2: "{{ data['ip_int_g0/2'] }}"

  tasks:
    ##### loop create OSPF #####
    - name: configure OSPF
      ios_config:
        lines:
          - network {{ item }} area 0
        parents: router ospf 1
      with_items:
        - "{{ ospf_network[inventory_hostname] }}"

    ##### loop create interface g0/2 of each router ####
    - name: configure ip at g0/2 to all router
      ios_config:
        lines:
          - description test config loopback
          - ip address {{ item }}
          - no shutdown
        parents: interface g0/2
      with_items:
        - "{{ ip_int_g2[inventory_hostname] }}"
      backup: yes
        backup_options: #backup runningconfig to text file
          dir_path: /home/devasc/npa_project
          filename: run_config.txt

    ##### delete ip on interface #####
    - name: delete ip
      ios_config:
        lines:
          - no ip add
        parents: int g0/2

    ##### delete OSPF #####
    - name: delete OSPF
      ios_config:
        lines:
          - no router ospf 1